namespace PodcastTycoon.Core
{
    /// <summary>
    /// Everything "the week happens" produces, before the player picks a topic.
    /// The appeal multipliers here are consumed by <see cref="Resolution"/>.
    /// </summary>
    public sealed class WeekContext
    {
        public int Turn;                    // season turn (1-based)
        public int GlobalWeek;              // lifetime week (1-based)
        public int Season;                  // 1-based

        public Fixture Fixture;
        public MatchResult Match;           // null on a matchless week
        public int LeaguePosition;
        public string LeaguePositionLabel;  // "7th"

        public bool IsInternationalBreak => Fixture != null && Fixture.IsInternationalBreak;
        public bool IsOffseason => Fixture != null && Fixture.IsOffseason;
        public bool IsCupByeWeek => Fixture != null && Fixture.IsCupByeWeek;
        public bool IsMatchless => Fixture == null || Fixture.IsMatchless;

        public Competition Competition => Fixture?.Competition ?? Competition.League;
        public bool IsCupTie => Fixture != null && Fixture.Competition == Competition.Cup && !Fixture.IsCupByeWeek;
        public bool IsEuropeanNight => Fixture != null && Fixture.Competition == Competition.European;

        public Surprise Surprise => Match?.Surprise ?? Surprise.Par;
        public FixtureImportance Importance => Fixture?.Importance ?? FixtureImportance.Normal;

        /// <summary>A line about a cup result / European night / trophy, if any.</summary>
        public string CompetitionNote;

        /// <summary>Set on the last few weeks of the season — the transfer window is open.</summary>
        public bool TransferWindowOpen;

        // --- rivals (slice 3) ---
        public System.Collections.Generic.List<string> RivalNews = new System.Collections.Generic.List<string>();
        public bool AnyRivalStumbled;
        public bool AnyRivalSurged;
        public bool IsRivalMatch => Fixture != null && Fixture.IsRivalFixture;

        // --- match moments (slice 3) ---
        public System.Collections.Generic.List<string> Moments = new System.Collections.Generic.List<string>();
        public bool HasDramaticMoment;

        // --- a scoop awaiting your decision (slice 3, spec §14) ---
        public Scoop PendingScoop;
        public string ScoopOutcome;

        // --- access tier changes this week ---
        public int AccessTier;
        public string AccessNote;

        // --- a card offered this week (slice 3E) ---
        public System.Collections.Generic.List<string> CardsGained = new System.Collections.Generic.List<string>();

        // --- resolved context modifiers (filled by ContextResolver) ---
        public float ReachMult = 1f;
        public float PassiveGainRate;       // fraction of listeners gained regardless of episode
        public float MoodChurnRate;         // fraction lost if the episode is weak
        public float ImportanceAppealMult = 1f;
        public int SocialMultiplier = 1;

        /// <summary>A short line describing what kind of week this is, for the UI.</summary>
        public string Headline;

        /// <summary>A longer line on what this week's mood means for the episode you make.</summary>
        public string Advice;

        /// <summary>Injuries, returns, call-ups and form swings that happened this week.</summary>
        public System.Collections.Generic.List<string> SquadNews = new System.Collections.Generic.List<string>();

        /// <summary>How many key players were missing for this week's match.</summary>
        public int KeyPlayersOut;

        /// <summary>Topics generated by running story threads this week (spec §8).</summary>
        public System.Collections.Generic.List<Topic> ThreadTopics = new System.Collections.Generic.List<Topic>();

        /// <summary>One-line status lines for each running thread, for the match panel.</summary>
        public System.Collections.Generic.List<string> ThreadNotes = new System.Collections.Generic.List<string>();

        /// <summary>The currently running story threads.</summary>
        public System.Collections.Generic.List<StoryThread> ActiveThreads = new System.Collections.Generic.List<StoryThread>();

        /// <summary>Threads that opened or resolved at the start of this week.</summary>
        public System.Collections.Generic.List<ThreadEvent> ThreadEvents = new System.Collections.Generic.List<ThreadEvent>();

        /// <summary>An interrupt event awaiting the player's choice this week (spec §10).</summary>
        public GameEvent PendingEvent;

        /// <summary>Text describing the choice the player made on this week's event.</summary>
        public string EventOutcome;

        /// <summary>Sponsor offers currently on the table (spec §16).</summary>
        public System.Collections.Generic.List<SponsorOffer> SponsorInbox;

        /// <summary>The signed sponsor deal, if any.</summary>
        public ActiveSponsor ActiveSponsor;

        /// <summary>A sponsor deal that succeeded or failed at the start of this week.</summary>
        public SponsorNews SponsorNews;
    }

    public static class ContextResolver
    {
        public static void Fill(WeekContext c)
        {
            c.ReachMult = 1f;
            c.PassiveGainRate = 0f;
            c.MoodChurnRate = 0f;
            c.ImportanceAppealMult = 1f;
            c.SocialMultiplier = 1;

            if (c.IsOffseason)
            {
                c.ReachMult = 0.88f;
                c.SocialMultiplier = 2;
                c.TransferWindowOpen = true;
                c.Headline = "Transfer window — no football, but the rumour mill is at full tilt.";
                c.Advice = "Quiet for match content, loud for transfers. Speculation and squad-planning episodes do well; recaps fall flat.";
                return;
            }

            if (c.IsInternationalBreak)
            {
                c.ReachMult = 0.80f;
                c.Headline = "International break — no club game this week.";
                c.Advice = "Fewer people tuning in with no club game. A good week for the mailbag or a tier list.";
                return;
            }

            if (c.IsCupByeWeek)
            {
                c.ReachMult = 0.9f;
                c.Headline = "Cup weekend — you're watching this one from the sofa.";
                c.Advice = "No game of your own. Evergreen content, or a look at who's still in the cup.";
                return;
            }

            switch (c.Surprise)
            {
                case Surprise.Heroic:
                    c.PassiveGainRate = 0.020f;
                    c.Headline = "A famous result. Everyone wants to hear about this one.";
                    c.Advice = "New listeners are arriving on their own. A reaction episode will reach far — don't waste it on filler.";
                    break;
                case Surprise.Good:
                    c.PassiveGainRate = 0.010f;
                    c.Headline = "A good day. The mood is up.";
                    c.Advice = "The feel-good angle plays well right now. A recap or a vibes episode both land.";
                    break;
                case Surprise.Par:
                    c.Headline = "Roughly what everyone expected.";
                    c.Advice = "No strong story from the result. This is when evergreen content — a tier list, tactics, the mailbag — earns its keep.";
                    break;
                case Surprise.Poor:
                    c.MoodChurnRate = 0.010f;
                    c.Headline = "A frustrating one. The fanbase is grumbling.";
                    c.Advice = "There's appetite for a strong opinion. A sharp hot take draws well — but it costs you reputation.";
                    break;
                case Surprise.Disaster:
                    c.MoodChurnRate = 0.025f;
                    c.Headline = "A disaster. Handle this badly and people will switch off.";
                    c.Advice = "Crisis content peaks now. A well-argued take can grow the show off the back of it — a lazy episode will bleed listeners.";
                    break;
            }

            if (c.Importance != FixtureImportance.Normal)
            {
                c.ImportanceAppealMult = c.Importance == FixtureImportance.Final ? 1.55f : 1.30f;
                c.SocialMultiplier = c.Importance == FixtureImportance.Final ? 3 : 2;
                string tag = c.Importance switch
                {
                    FixtureImportance.Derby => "Derby week. ",
                    FixtureImportance.Final => "CUP FINAL. ",
                    _ => "Big match. "
                };
                if (c.IsCupTie && c.Importance != FixtureImportance.Final) tag = "Cup tie. ";
                if (c.IsEuropeanNight) tag = "European night. ";
                c.Headline = tag + c.Headline;
                c.Advice = "Everything is bigger this week — more reach and more attention on whatever you cover. " + c.Advice;
            }
            else if (c.IsCupTie)
            {
                c.ImportanceAppealMult = 1.15f;
                c.Headline = "Cup tie. " + c.Headline;
            }
        }

        /// <summary>Context appeal multiplier for a topic, by how it responds to the result (spec §5).</summary>
        public static float AppealMultiplier(TopicResponse response, WeekContext c)
        {
            if (c.IsOffseason)
            {
                switch (response)
                {
                    case TopicResponse.Reaction: return 0.60f;
                    case TopicResponse.Positive: return 0.70f;
                    case TopicResponse.Crisis: return 0.60f;
                    default: return 1.00f;
                }
            }

            if (c.IsInternationalBreak)
            {
                switch (response)
                {
                    case TopicResponse.Reaction: return 0.55f;
                    case TopicResponse.Positive: return 0.60f;
                    case TopicResponse.Crisis: return 0.50f;
                    default: return 0.90f;
                }
            }

            switch (response)
            {
                case TopicResponse.Reaction:
                    switch (c.Surprise)
                    {
                        case Surprise.Heroic: return 1.80f;
                        case Surprise.Good: return 1.40f;
                        case Surprise.Par: return 1.00f;
                        case Surprise.Poor: return 0.90f;
                        default: return 0.70f; // Disaster
                    }
                case TopicResponse.Positive:
                    switch (c.Surprise)
                    {
                        case Surprise.Heroic: return 1.70f;
                        case Surprise.Good: return 1.35f;
                        default: return 0.60f;
                    }
                case TopicResponse.Crisis:
                    switch (c.Surprise)
                    {
                        case Surprise.Disaster: return 2.00f;
                        case Surprise.Poor: return 1.50f;
                        case Surprise.Par: return 0.85f;
                        case Surprise.Good: return 0.55f;
                        default: return 0.45f; // Heroic
                    }
                case TopicResponse.Evergreen:
                default:
                    return 1.00f;
            }
        }
    }
}
